imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: cs/service_app.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '/tmp/session'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
          Calls:
              is_bundle: false
              type: xml
              prefix: CS\ServiceApp\Call\Domain
              dir: %kernel.root_dir%/../src/CS/ServiceApp/Call/Infrastructure/Doctrine/mapping
              alias: ServiceApp\Call
          Forms:
              is_bundle: false
              type: xml
              prefix: CS\ServiceApp\Form\Domain
              dir: %kernel.root_dir%/../src/CS/ServiceApp/Form/Infrastructure/Doctrine/mapping
              alias: ServiceApp\Form
          Sms:
              is_bundle: false
              type: xml
              prefix: CS\ServiceApp\Sms\Domain
              dir: %kernel.root_dir%/../src/CS/ServiceApp/Sms/Infrastructure/Doctrine/mapping
              alias: ServiceApp\Sms
          Client:
              is_bundle: false
              type: xml
              prefix: CS\ServiceApp\Client\Domain
              dir: %kernel.root_dir%/../src/CS/ServiceApp/Client/Infrastructure/Doctrine/mapping
              alias: ServiceApp\Client
# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\Client
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
