call:
  path: /
  defaults: { _controller: service_app.controller.call:indexAction }

premium_content:
  path: /premium
  defaults: { _controller: service_app.controller.premium_content:premiumAction }

request_form:
  path: /form/{id}
  defaults: { _controller: service_app.controller.form:formAction }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
