---
- name: Running custom commands
  shell: php app/console {{item.command}} {{item.args}} {{deploy.project.php.symfony2.console_opts}} --env={{deploy.project.php.symfony2.env}}
  args:
    chdir: "{{deploy.project.root}}/releases/{{project_deploy_date.stdout}}"
  ignore_errors: yes
  with_items: "{{deploy.project.php.symfony2.custom_commands}}"
  when: deploy.project.php.symfony2.custom_commands
