- name: Register release variable
  shell: date +%Y%m%d%H%M%S
  register: project_deploy_date


- name: Check if current release exists
  shell: readlink "{{deploy.project.root}}/current"
  register: checking_result
  ignore_errors: yes

- name: Register fact - Current relese exists
  set_fact:
      current_release_exists: true
  when: checking_result.failed is not defined

- name: Register fact - Current relese don't exists
  set_fact:
      current_release_exists: false
  when: checking_result.failed is defined

- name: Register path of current release
  set_fact:
    current_release_path: "{{ checking_result.stdout }}"
  when: current_release_exists

- name: Register last basename
  shell: echo $(basename {{ current_release_path }})
  register: last_release
  when: current_release_exists

- name: Create variable.
  set_fact:
    next_release: "{{ project_deploy_date.stdout }}"

- name: Create variable.
  set_fact:
    current_release: "{{ last_release.stdout }}"
  when: current_release_exists

