---
- name: Define variables.
  set_fact:
    project_owner: "{{ ansible_user }}"
  when: project_owner is not defined

- name: Define variables.
  set_fact:
    owner_group: "{{ ansible_user }}"
  when: owner_group is not defined
# tasks file for project setup

- name: Create the release directory.
  file:
    state=directory
    path={{deploy.project.root}}/releases

- name: Create the shared directory.
  file:
    state=directory
    path={{deploy.project.root}}/shared

- name: Change owner
  file: owner="{{project_owner}}" group="{{owner_group}}" dest="{{deploy.project.root}}"
